site_name: Plateforme de documentation en Géomatique
site_description: Cours, travaux pratiques et projets en géomatique
site_author: Abdoulhakim ELMI MAHAMOUD

theme:
  name: readthedocs
  locale: fr

nav:
  - Accueil: index.md

  - OpenLayers:
      - Cours théorique: openlayers/cours.md
      - Travaux pratiques: openlayers/pratique.md
      - Schémas: openlayers/schemas.md
